// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupSave(arg1:string):Promise<main.Result>;

export function DeleteSave(arg1:string):Promise<boolean>;

export function GetBackups():Promise<Array<main.BackupInfo>>;

export function RestoreSave(arg1:string):Promise<main.Result>;
