// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupSave(arg1) {
  return window['go']['main']['App']['BackupSave'](arg1);
}

export function DeleteSave(arg1) {
  return window['go']['main']['App']['DeleteSave'](arg1);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function RestoreSave(arg1) {
  return window['go']['main']['App']['RestoreSave'](arg1);
}
