// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup_save(arg1:string):Promise<string>;

export function Restore_save(arg1:string):Promise<void>;
