// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup_save(arg1) {
  return window['go']['main']['App']['Backup_save'](arg1);
}

export function Restore_save(arg1) {
  return window['go']['main']['App']['Restore_save'](arg1);
}
